- name: Install NFS packages
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Ensure NFS export path exists
  file:
    path: "{{ export_path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Configure exports for NFS
  copy:
    dest: "/etc/exports.d/{{ export_path | basename }}.exports"
    content: |
      {{ export_path }} {{ export_clients }}(rw,sync,no_subtree_check,no_root_squash)

- name: Ensure NFS service is started and enabled
  systemd:
    daemon_reload: yes
    name: nfs-server
    enabled: yes
    state: restarted