- name: Install NFS client packages
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Ensure mount point directories exist
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - { path: /mnt/monitoring }
    - { path: /mnt/logs }

- name: Mount NFS shares
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: nfs
    opts: defaults
    state: mounted
  loop:
    - { path: /mnt/monitoring, src: 192.168.8.161:/data/monitoring }
    - { path: /mnt/logs,       src: 192.168.8.162:/data/logs }

- name: Ensure NFS mounts are persistent in fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ item.src }} {{ item.path }} nfs defaults 0 0"
    state: present
  loop:
    - { path: /mnt/monitoring, src: 192.168.8.161:/data/monitoring }
    - { path: /mnt/logs,       src: 192.168.8.162:/data/logs }