all:
  children:
    controlplane:
      hosts:
        master01:
          ansible_host: 192.168.8.129
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    workers:
      hosts:
        worker01:
          ansible_host: 192.168.8.161
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        worker02:
          ansible_host: 192.168.8.162
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa